#!/usr/bin/env python3
"""Render the introduction page with version + changelog placeholders filled in.

The introduction/index.html file uses placeholder tokens:
  {{VERSION}}            e.g. 0.1.1
  {{RELEASE_DATE}}       e.g. 2026-07-12
  {{PROTOCOL}}           e.g. TC1
  {{DECK_SIZE}}          e.g. 78
  {{CHANGELOG_SUMMARY}}  latest CHANGELOG.md bullet list joined into one line

This module:
  - reads the latest released version from CHANGELOG.md (the most recent `[x.y.z]` heading)
  - reads the matching section's bullet points
  - renders a standalone copy at dist/tarot-confessional-<version>/introduction.html
    with all placeholders substituted, so the marketing page can be hosted next
    to the skill package.

The source-of-truth (`introduction/index.html`) is left alone until
`scripts/package_skill.py` invokes this module — at which point the
dist-side copy is regenerated.

Usage:
    python3 scripts/render_introduction.py --version 0.1.1
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INTRODUCTION_TEMPLATE = ROOT / "introduction" / "index.html"
CHANGELOG = ROOT / "CHANGELOG.md"

PLACEHOLDER_RE = re.compile(r"\{\{[A-Z_]+\}\}")


def latest_release_entry(changelog: str, requested_version: str) -> tuple[str, list[str]]:
    """Return (release_date_str, bullets[]) for the requested version block.

    Falls back to the most recent entry when the requested version is not in
    CHANGELOG yet (e.g. integration tests use a synthetic version).
    """
    pattern = re.compile(
        r"^## \[(?P<v>[0-9]+\.[0-9]+\.[0-9]+)\] - (?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2}).*?(?=^## \[|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    entries = list(pattern.finditer(changelog))
    for match in entries:
        if match.group("v") == requested_version:
            block = match.group(0)
            date = match.group("date")
            bullets = re.findall(r"^- (.+)$", block, re.MULTILINE)
            return date, bullets
    if entries:
        latest = entries[0]
        return latest.group("date"), re.findall(r"^- (.+)$", latest.group(0), re.MULTILINE)
    return datetime.now(timezone.utc).strftime("%Y-%m-%d"), ["首次发布"]


def collect_substitutions(skill_dir: Path, version: str) -> dict[str, str]:
    changelog = CHANGELOG.read_text(encoding="utf-8")
    date_str, bullets = latest_release_entry(changelog, version)
    deck_size = _count_card_images(skill_dir / "assets" / "images" / "cards")
    return {
        "VERSION": version,
        "RELEASE_DATE": date_str,
        "PROTOCOL": "TC1",
        "DECK_SIZE": str(deck_size),
        "CHANGELOG_SUMMARY": " · ".join(bullets[:3]) if bullets else "首次正式发布",
    }


def _count_card_images(cards_dir: Path) -> int:
    if not cards_dir.is_dir():
        return 0
    return len([p for p in cards_dir.glob("*.jpg") if p.is_file()])


def render(template: str, substitutions: dict[str, str]) -> tuple[str, list[str]]:
    expected = set(PLACEHOLDER_RE.findall(template))
    missing = expected - {f"{{{{{key}}}}}" for key in substitutions}
    if missing:
        # Refuse to silently leave placeholders blank — surface them to the
        # caller (which currently always supplies every key, so missing is
        # only possible for an unknown placeholder token).
        raise KeyError(f"template has placeholders without substitution keys: {sorted(missing)}")
    filled = template
    for key, value in substitutions.items():
        filled = filled.replace(f"{{{{{key}}}}}", value)
    return filled, []  # substitutions are exhaustive; leftover no longer meaningful


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--skill-dir", type=Path, default=ROOT / "skills" / "tarot-confessional")
    parser.add_argument("--output", type=Path, default=None,
                        help="default: introduction/index.html (in-place). The packaged copy in dist is regenerated by package_skill.py.")
    parser.add_argument("--stamped-output", type=Path, default=None,
                        help="optional output for the dist-side rendered copy with placeholders filled.")
    args = parser.parse_args()

    template = INTRODUCTION_TEMPLATE.read_text(encoding="utf-8")
    substitutions = collect_substitutions(args.skill_dir, args.version)
    try:
        rendered, _ = render(template, substitutions)
    except KeyError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(f"rendered source copy: {args.output}")
    if args.stamped_output:
        args.stamped_output.parent.mkdir(parents=True, exist_ok=True)
        stamped = f"<!-- rendered at {datetime.now(timezone.utc).isoformat(timespec='seconds')} for v{args.version} -->\n" + rendered
        args.stamped_output.write_text(stamped, encoding="utf-8")
        print(f"rendered dist copy:    {args.stamped_output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())